@extends('layout')

@section('title', 'Terms of Use')

@section('additional_styles')
    <style>
        ul.tooltips_demo {
            list-style:none;
            margin:0;
            padding:0;
        }
        ul.tooltips_demo li{
            margin-right:20px;
            display:inline-block;
        }
    </style>
@endsection

@section('additional_javascript')
@endsection

@section('hero')
    <section id="hero">
        <div class="intro_title">
            <h3 class="animated fadeInDown">Discover 3,840 classes around <a href="{{ route('coverage') }}">the globe</a></h3>
			<p class="animated fadeInDown">All the knowledge you need from Coding to Music, taught by our global community of teachers.</p>
			{{--<a href="#" class="animated fadeInUp button_intro">View Tours</a> <a href="#" class="animated fadeInUp button_intro outline">View Tickets</a>--}}
        </div>
    </section><!-- End hero -->

    <div id="position">
        <div class="container">
            <ul>
                <li><a href="{{ route('homepage') }}">Home</a></li>
                <li>Terms of Use</li>
            </ul>
        </div>
    </div><!-- Position -->
@endsection

@section('content')
    <div class="container margin_60">
        <div class="row">

            <div class="col-lg-12 col-md-8 col-sm-8">

                <div class="row">
                    <div class="col-md-12">

                        <!-- Headings & Paragraph Copy -->
                        <h1>Terms of Use</h1>
                        <h2>January 1, 2017</h2>
                        <p> These terms and conditions ("User Terms") apply to your visit to and your use of our website at www.classrr.com (the "Website," "Site") and the Service, as well as to all information, recommendations and/or services provided to you on or through the Website and the Service. </p>
                        <p>PLEASE READ THESE TERMS OF SERVICE CAREFULLY. BY ACCESSING OR USING CLASSRR. APPLICATIONS OR ANY SERVICES PROVIDED BY US, YOU AGREE TO BE BOUND BY THESE TERMS OF SERVICE. IF YOU DO NOT AGREE TO ALL OF THESE TERMS AND CONDITIONS, DO NOT ACCESS OR USE CLASSRR. APPLICATIONS OR ANY SERVICES PROVIDED BY US.</p>
                        <h2>CLASSRR, Inc.</h2>
                        <p>Your contracting partner is Classrr, Inc., a corporation established in Singapore.</p>
                        <h2>How is a contract concluded between Classrr and you?</h2>
                        <p>By using the Website, Application or the Service, you enter into a contract with Classrr (the "Contract"). In order to be able to fully use the Website, Application or Service, you first need to sign up with Classrr. When signing up, you are obligated to provide Classrr with your personal information, and email address. Upon successful completion of your signing up with Classrr, Classrr will provide you with a personal account, which may be accessible for you with a password of your choice.</p>
                        <p>You have to be 18 years of age or older to use the Service, Website, or Application. If you reside in a jurisdiction that restricts the use of the Service, Website, or Application because of age, or restricts the ability to enter into contracts such as this one due to age, you must abide by such age limits and you must not use the Service and the Application. You represent that if you are an individual, you are of legal age to enter into a binding contract, or that if you are registering on behalf of a legal entity, that you are authorized to enter into, and bind the entity to, these User Terms and register for the Service and the Application.</p>
                        <h2>User Responsibilities</h2>
                        <p>Neutral Venue. Our Site is an online venue through which users find and learn about each other. Our Site is merely a venue for users to learn about one another and, if they wish, arrange study with one another. We are not involved in the actual face-to-face contact between users. As a result, we have no control over the conduct of our users or the truth or accuracy of the information that users post on the Site.</p>
                        <p>Identity Verification. We make no attempt to confirm, and do not confirm, any user's purported identity. You are responsible for determining the identity and suitability of others who you may contact by means of this Site. We do not endorse any persons who use or register for our Services, whether as students or teachers. We do not investigate any user's reputation, conduct, morality, criminal background, or verify the information that any user submits to the Site. We encourage you to communicate directly with potential teachers and students through the tools available on the Site and to review your teachers' and students' profile pages for feedback from other users.</p>
                        <p>Your Experience with Other Users. You are solely responsible for your interactions with other users of our Services. We will not be responsible for any damage or harm resulting from your interactions with other users of our Services. We reserve the right, but have no obligation, to monitor interactions between you and other users of our Services and to take any other action in good faith to restrict access to or the availability of any material that we or another user of our Services may consider obscene, lewd, lascivious, filthy, violent, harassing or otherwise objectionable.</p>
                        <p>Release. By using the Site or Services, you agree that any legal remedy or liability that you seek to obtain for actions or omissions of other users will be limited to a claim against the particular user or users who caused you harm. You agree not to attempt to impose liability on, or seek any legal remedy from Classrr.;  You release Classrr from any and all claims, demands, damages (actual, consequential, nominal, punitive, or otherwise), equitable relief, and any other legal, equitable, and administrative remedy, of every kind and nature, whether known or unknown, suspected or unsuspected, disclosed or undisclosed, past, present, or future, arising out of or in any way connected with your communication or interaction with other users on the Site or your experience as a guest or host in connection with the Site.</p>
                        <h2>Your use of the Website, Application, or the Service</h2>
                        <p>You warrant that the information you provide to Classrr is accurate and complete. Classrr is entitled at all times to verify the information that you have provided and to refuse the Service or use of the Application without providing reasons.</p>
                        <p>You may only access the Service using authorized means. It is your responsibility to check to ensure you download the correct Application for your device. Classrr is not liable if you do not have a compatible mobile device or if you download the wrong version of the Application for your mobile device. Classrr reserves the right to terminate the Service and the use of the Application should you be using the Service or Application with an incompatible or unauthorized device.</p>
                        <h2>User Conduct</h2>
                        <h4>By using the Website, Application or the Service, you further agree that:</h4>
                        <ul>
                            <li>You will only use the Service, Website, or download the Application for your sole, personal use and will not resell it to a third party;</li>
                            <li>You will not authorize others to use your account;</li>
                            <li>You will not assign or otherwise transfer your account to any other person or legal entity;</li>
                            <li>You will not use an account that is subject to any rights of a person other than you without appropriate authorization;</li>
                            <li>You will not use the Service, Website, or Application for unlawful purposes, including but not limited to sending or storing any unlawful material or for fraudulent purposes;</li>
                            <li>You will not use the Service , Website, or Application to cause nuisance, annoyance or inconvenience;</li>
                            <li>You will not impair the proper operation of the network; You will not try to harm the Service , Website, or Application in any way whatsoever;</li>
                            <li>You will not copy, or distribute the Website, Application, or other Classrr Content without written permission from Classrr;</li>
                            <li>You will keep secure and confidential your account password or any identification we provide you which allows access to the Service, Website, and the Application;</li>
                            <li>You will provide us with whatever proof of identity we may reasonably request;</li>
                            <li>You will not use the Service, Website, or Application with an incompatible or unauthorized device;</li>
                            <li>You will comply with all applicable law from your home nation, the country, state and/or city in which you are present while using the Application, Website, or Service.</li>
                            <li>You will not register for more than one user account or register for a user account on behalf of an individual other than yourself;</li>
                            <li>You will not use automated scripts to collect information or otherwise interact with the Service or the Site;</li>
                            <li>You will not use the site to find a teacher or student and then complete the transaction offline in order to circumvent your obligation to pay for the Service;</li>
                            <li>You will not submit any listing with a false or misleading price, or submit any listing with a price that you do not intend to honor or advocate, encourage, or assist any third party in doing any of the foregoing;</li>
                            <li>Classrr reserves the right to immediately terminate the Service and the use of the Website or Application should you not comply with any of the above rules.</li>
                        </ul>
                        <p>Disputes with Other Users. You are solely responsible for your interactions with other Classrr users. We reserve the right, but have no obligation, to monitor disputes between you and other users.</p>
                        <p>Listing Prices. If you post a listing offering service through the Site which is accepted by you and a student, you acknowledge and agree that the price you specify for that listing will constitute an essential part of a binding agreement between you and the student. You further agree not to alter the price once accepted.</p>
                        <p>MINORS MAY NOT USE SERVICES. You must be at least 18 years old to register to use the Services. By registering to use our Services, you represent that you are over 18.</p>
                        <p>PRIVACY. The Privacy Policy of Classrr is available on the Site at https://www.classrr.com/terms and is hereby incorporated by reference. You agree to abide by all terms set forth in the Privacy Policy.</p>
                        <h2>Payment</h2>
                        <p>The use of the Website and Application is free of charge. Classrr reserves the right to introduce a fee for the use of the Application. If Classrr decides to introduce such a fee, Classrr shall inform you accordingly and allow you to either continue or terminate the Contract.</p>
                        <p>Classrr may use a third-party payment processor (the "Payment Processor") to link your credit card account to the Application and Service. The processing of payments or credits, as applicable, in connection with your use of the Website, Application and Service will be subject to the terms, conditions and privacy policies of the Payment Processor and your credit card issuer in addition to these User Terms. Classrr is not responsible for any errors by the Payment Processor. In connection with your use of the Services, Classrr will obtain certain transaction details, which Classrr will use solely in accordance with its Privacy Policy.</p>
                        <p>Fee Structure. In exchange for providing the Service, Classrr keeps a small portion of the teacher's price of each class schedule. As a student, you agree to pay the amount posted by the teacher with whom you have chosen to study with. As a teacher, posting a listing is free, but you agree to pay Classrr its then-current service charge for each student's class.</p>
                        <p>Payment Logistics. If you find a listing that you are interested in, you will be asked to provide your credit card information and billing address. We will obtain a pre-authorization for the total amount of the study to ensure that you have the necessary amount of funds available to cover the transaction, but will not charge your card at that time. If the teacher who posted the listing accepts your offer, your card will be charged at the time of acceptance; if the posting user fails to respond or opts not to accept your offer, your card will not be charged, and the pre-authorization will be released. The funds will be held by Classrr until the study has started; at that time, Classrr will remit the held funds to the teacher, less Classrr's service charge.</p>
                        <p>Cancellation and Refunds. If you cancel your reservation request, Classrr will return the funds to you in accordance with its cancellation policy. No refunds are provided after the first date of your study for any reason. Classrr is a reputation-based system. If a service is not provided as listed, your sole remedy is to provide feedback on your teacher via the Service.</p>
                        <p>Donations. Some teachers may pledge to donate a portion of the funds they receive to a particular cause or charity. We do not control, and will not take any responsibility or liability for, whether the host does in fact make the donation they pledged to make.</p>
                        <p>Privacy. Our privacy policy governs the handling, storage, and use of any information you submit to us, including credit card billing information.</p>
                        <p>Taxes. You understand that we are acting solely as an intermediary for the collection of payments and fees between you and any teachers or students with whom you choose to enter into a transaction. Because state and local tax laws vary significantly by locality, you understand and agree that you are solely responsible for determining your own tax reporting requirements in consultation with tax advisors, and that we cannot and do not offer tax advice to either teachers or students.</p>

                        <h2>Indemnification</h2>
                        <p>By accepting these User Terms and using the Application or Service, you agree that you shall defend, indemnify and hold Classrr, its affiliates, its licensors, and each of their officers, directors, other users, employees, attorneys and agents harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including attorneys' fees and costs) arising out of or in connection with: (a) your violation or breach of any term of these User Terms or any applicable law or regulation, whether or not referenced herein; (b) your violation of any rights of any third party, or (c) your use or misuse of the Application or Service.</p>
                        <h2>Liability</h2>
                        <p>The information, recommendations and/or services provided to you on or through the Website, the Service and the Application is for general information purposes only and does not constitute advice. Classrr will reasonably keep the Website and the Application and its contents correct and up to date but does not guarantee that (the contents of) the Website and/or Application are free of errors, defects, malware and viruses or that the Website and/or Application are correct, up to date and accurate.</p>
                        <p>Classrr shall not be liable for any damages resulting from the use of (or inability to use) the Website or Application (but to the exclusion of death or personal injury), including damages caused by malware, viruses or any incorrectness or incompleteness of the Information or the Website or Application, unless such damage is the result of any wilful misconduct or from gross negligence on the part of Classrr.</p>
                        <p>Classrr shall further not be liable for damages resulting from the use of (or the inability to use) electronic means of communication with the Website or the Application, including – but not limited to – damages resulting from failure or delay in delivery of electronic communications, interception or manipulation of electronic communications by third parties or by computer programs used for electronic communications and transmission of viruses.</p>
                        <h2>License Grant, Restrictions and Copyright Policy</h2>
                        <p>For the purpose of this User Term, the following definitions apply:</p>
                        <p>"Content" means all content featured or displayed, including, but not limited to, logos, icons, trademarks, text, graphics text, graphics, photographs, images, moving images, sound, illustrations, music, software (excluding the Application), opinions, remarks, comments, artwork, links, questions, suggestions, information or other materials.</p>
                        <p>"Classrr Content" means Content owned or used by Classrr, its affiliates or licensors and made available through the Website, Service or Application, including any Content licensed from a third party, but excluding User Content.</p>
                        <p>"User" means a person who accesses or uses the Service or Application.</p>
                        <p>"User Content" means Content that a User posts, uploads, publishes, submits or transmits to be made available on the Website or through the Service or Application.</p>
                        <p>"Collective Content" means, collectively, Classrr Content and User Content.</p>
                        <p>Subject to your compliance with these User Terms, Classrr grants you a limited, non-exclusive, non-transferable license:</p>
                        <p>(i) to view, download and print any Classrr Content solely for your personal and non-commercial purposes; and</p>
                        <p>(ii) to view any User Content to which you are permitted access solely for your personal and non-commercial purposes.</p>
                        <p>You have no right to sublicense the license rights granted in this section.</p>
                        <p>You may not use, copy, adapt, modify, create derivative works from, distribute, license, sell, transfer, publicly display, publicly perform, reproduce, transmit, stream, broadcast or otherwise exploit the Website, Service, Application or Collective Content, except as expressly permitted in these User Terms. You may not reuse any Collective Content without first obtaining the written consent of Classrr. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by Classrr or its licensors, except for the licenses and rights expressly granted in these User Terms.</p>
                        <h2>License granted by User</h2>
                        <p>We may, in our sole discretion, permit Users to post, upload, publish, submit or transmit User Content on the Website or through the Service or Application. User Content will be deemed non-confidential and non-proprietary. Accordingly, Classrr shall have the non-exclusive, royalty-free, right to use, copy, distribute and disclose to third parties any User Content for any purpose, in any medium and throughout the world ("License Grant").</p>
                        <p>You acknowledge that Classrr only acts as a passive conduit for the distribution of the User Content and is not responsible or liable to you or to any third party for the content or accuracy of the User Content. Classrr shall not be continuously monitoring User Content published by you or moderating between Users, nor shall Classrr be under an obligation to do so. Without limiting the foregoing, you acknowledge and agree that any remarks, opinions, comments, suggestions and other information expressed or included in the User Content do not necessarily represent those of Classrr.</p>
                        <p>Any use by you of the User Content is entirely at your own risk. You represent and warrant that any User Content posted or transmitted by you is original to you and does not copy the work of any third party or otherwise infringe any third party intellectual property rights, rights of privacy or personality rights and does not contain any defamatory or disparaging statements. Furthermore, you represent and warrant that you have the capacity to grant the license as stipulated in this paragraph.</p>
                        <p>You agree to indemnify and keep Classrr, its affiliates and licensors indemnified against all costs, expenses, damages, losses and liabilities incurred or suffered by Classrr or its affiliated companies related to any User Content posted or transmitted by you or your other use of the Website, the Service or the Application.</p>
                        <p>Classrr reserves the right at its sole discretion to block or remove (in whole or in part) any User Content posted or transmitted by you and which Classrr believes is not in accordance with these User Terms (including materials which infringe or may infringe third party intellectual property rights, rights of privacy or personality rights), or is otherwise unacceptable to Classrr.</p>
                        <p>You agree to promptly notify Classrr in writing of any User Content which breaches these User Terms. You agree to provide to Classrr sufficient information to enable Classrr to investigate whether such User Content breaches these User Terms. Classrr agrees to make good faith efforts to investigate such complaint and shall take such action as Classrr in its sole discretion decides. However, Classrr does not warrant or represent that it will block or remove (in whole or in part) such user Content.</p>
                        <h2>Application License</h2>
                        <p>Subject to your compliance with these User Terms, Classrr grants you a limited non-exclusive, non-transferable license to download and install a copy of the Application on a single mobile device that you own or control and to run such copy of the Application solely for your own personal use.</p>
                        <p>You shall not (i) license, sublicense, sell, resell, transfer, assign, distribute or otherwise commercially exploit or make available to any third party the Service or Application in any way; (ii) modify or make derivative works based upon the Service or Application; (iii) create Internet "links" to the Service or "frame" or "mirror" any Application on any other server or wireless or Internet-based device; (iv) reverse engineer or access the Application in order to (a) design or build a competitive product or service, (b) design or build a product using similar ideas, features, functions or graphics of the Service or Application, or (c) copy any ideas, features, functions or graphics of the Service or Application, or (v) launch an automated program or script, including, but not limited to, web spiders, web crawlers, web robots, web ants, web indexers, bots, viruses or worms, or any program which may make multiple server requests per second, or unduly burdens or hinders the operation and/or performance of the Service or Application.</p>
                        <p>You shall not: (i) send spam or otherwise duplicative or unsolicited messages in violation of applicable laws; (ii) send or store infringing, obscene, threatening, libellous, or otherwise unlawful or tortious material, including material harmful to children or violative of third party privacy rights; (iii) send or store material containing software viruses, worms, Trojan horses or other harmful computer code, files, scripts, agents or programs; (iv) interfere with or disrupt the integrity or performance of the Website, the Application or Service or the data contained therein; or (v) attempt to gain unauthorized access to the Website, the Application or Service or its related systems or networks.</p>
                        <p>Classrr will have the right to investigate and prosecute violations of any of the above to the fullest extent of the law. Classrr may involve and cooperate with law enforcement authorities in prosecuting users who violate these User Terms. You acknowledge that Classrr has no obligation to monitor your access to or use of the Website, Service, Application or Collective Content or to review or edit any Collective Content, but has the right to do so for the purpose of operating the Website, the Application and Service, to ensure your compliance with these User Terms, or to comply with applicable law or the order or requirement of a court, administrative agency or other governmental body. Classrr reserves the right, at any time and without prior notice, to remove or disable access to any Collective Content that Classrr, at its sole discretion, considers to be in violation of these User Terms or otherwise harmful to the Website, the Service or Application.</p>
                        <h2>Intellectual Property Ownership</h2>
                        <p>Classrr alone (and its licensors, where applicable) shall own all right, title and interest, including all related intellectual property rights, in and to the Website, Application and the Service and any suggestions, ideas, enhancement requests, feedback, recommendations or other information provided by you or any other party relating to the Website, Application or the Service.</p>
                        <p>These User Terms do not constitute a sale and do not convey to you any rights of ownership in or related to the Website, the Application or the Service, or any intellectual property rights owned by Classrr. Classrr name, logo, and the product names associated with the Application and Service are trademarks of Classrr, its affiliated companies or third parties, and no right or license is granted to use them.</p>
                        <h2>App Store Sourced Application</h2>
                        <p>With respect to any Application accessed through or downloaded from the Apple App Store ("App Store Sourced Application"), you will use the App Store Sourced Application only: (i) on an Apple-branded product that runs iOS (Apple’s proprietary operating system software); and (ii) as permitted by the “Usage Rules” set forth in the Apple App Store Terms of Service. Classrr reserves all rights in and to the Application not expressly granted to you under these User Terms.</p>
                        <p>You acknowledge and agree that (i) these User Terms are valid between you and Classrr only, and not Apple, and (ii) Classrr, not Apple, is solely responsible for the App Store Sourced Application and content thereof. Your use of the App Store Sourced Application must comply with the App Store Terms of Service.</p>
                        <p>You acknowledge that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the App Store Sourced Application.</p>
                        <p>In the event of any failure of the App Store Sourced Application to conform to any applicable warranty, you may notify Apple, and Apple will, where applicable, refund the purchase price for the App Store Sourced Application to you and to the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the App Store Sourced Application. As between Classrr and Apple, any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be the sole responsibility of Classrr.</p>
                        <p>You and Classrr acknowledge that, as between Classrr and Apple, Apple is not responsible for addressing any claims you have or any claims of any third party relating to the App Store Sourced Application or your possession and use of the App Store Sourced Application, including, but not limited to: (i) product liability claims; (ii) any claim that the App Store Sourced Application fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation.</p>
                        <p>You and Classrr acknowledge that, in the event of any third party claim that the App Store Sourced Application or your possession and use of that App Store Sourced Application infringes that third party’s intellectual property rights, as between Classrr and Apple, Classrr, not Apple, will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim to the extent required by this Agreement.</p>
                        <p>You and Classrr acknowledge and agree that Apple, and Apple’s subsidiaries, are third party beneficiaries relating to your license of the App Store Sourced Application, and that, upon your acceptance of these User Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce the rights under these User Terms as related to your license of the App Store Sourced Application against you as a third party beneficiary thereof.</p>
                        <p>Without limiting any other provisions of these User Terms, you must comply with all applicable third party terms of agreement when using the App Store Sourced Application.</p>
                        <h2>Third Party Interactions</h2>
                        <p>During the use of the Website, the Application and the Service, links to websites that are owned and controlled by third parties may be provided from time to time in order to enter into correspondence with, purchase goods or services from, participate in promotions of third parties. These links take you off the Website, the Application and the Service and are beyond Classrr's control.</p>
                        <p>During use of the Website, the Application and the Service, you may enter into correspondence with, purchase goods and/or services from, or participate in promotions of third party service providers, advertisers or sponsors showing their goods and/or services through a link on the Website or through the Application or Service. These links take you off the Website, the Application and the Service and are beyond Classrr’s control. The websites you can link to have their own separate terms and conditions as well as a privacy policy. Classrr is not responsible and cannot be held liable for the content and activities of these websites. You therefore visit or access these websites entirely at your own risk.</p>
                        <p>Please note that these other websites may send their own cookies to users, collect data or solicit personal information, and you are therefore advised to check the terms of use or privacy policies on those websites prior to using them.</p>
                        <h2>Term and termination of the contract</h2>
                        <p>The Contract between Classrr and you is concluded for an indefinite period.</p>
                        <p>You are entitled to terminate the Contract at all times by permanent deletion of the Application installed on your smart phone, thus disabling the use by you of the Application and the Service. You can close your user account at any time by contact Classrr's customer support at <a href="mailto:contact@classrr.com">contact@classrr.com</a>.</p>
                        <p>Classrr is entitled to terminate the Contract at all times and with immediate effect (by disabling your use of the Application and the Service) if you: (a) violate or breach any term of these User Terms, or (b) in the opinion of Classrr, misuse the Application or the Service. In addition, Classrr may terminate the Contract if, in its sole judgment, you reside in a location that it deems unsafe to send employees. Classrr is not obliged to give notice of the termination of the Contract in advance. After termination Classrr will give notice thereof in accordance with these User Terms.</p>
                        <h2>Invalidity of one or more provisions</h2>
                        <p>The invalidity of any term of these User Terms shall not affect the validity of the other provisions of these User Terms.</p>
                        <p>If and to the extent that any provision of these User Terms is invalid, or is unacceptable in the given circumstances according to the criteria of reasonableness and fairness, a provision shall apply between the parties instead that is acceptable considering all the circumstances and which corresponds with the provisions of the void part as much as possible, taking into account the content and the purpose of these User Terms.</p>
                        <h2>Modification of the Service and User Terms</h2>
                        <p>Classrr reserves the right, at its sole discretion, to modify or replace any of these User Terms, or change, suspend, or discontinue the Service or Application (including without limitation, the availability of any feature, database, or content) at any time by posting a notice on the Website or by sending you notice through the Service, Application or via email. Classrr may also impose limits on certain features and services or restrict your access to parts or all of the Service without notice or liability.</p>
                        <h2>Notice</h2>
                        <p>Classrr may give notice by means of a general notice on the Service or Application, or by electronic mail to your email address on record in Classrr's account information, or by written communication sent by regular mail to your address on record in Classrr's account information.</p>
                        <h2>Assignment</h2>
                        <p>You may not assign your rights under these User Terms without prior written approval of Classrr.</p>
                        <h2>Privacy Policy</h2>
                        <p>Classrr may collect and processes the personal data of the visitors of the Website and users of the Application according to the Privacy Policy.</p>
                        <h2>Reporting Misconduct</h2>
                        <p>If you study with or teacher anyone who you feel is acting or has acted inappropriately, including but not limited to offensive, violent or sexually inappropriate behavior, who you suspect of stealing from you, or who engages in any other disturbing conduct, you must immediately report such person to the appropriate authorities and then to us by contacting us with your police station and report number at <a href="mailto:contact@classrr.com">contact@classrr.com</a>; provided that your report shall not obligate us to take any action beyond that required by law (if any) or cause us to incur any liability to you.</p>
                        <h2>Applicable law and Venue</h2>
                        <p>The Terms and your use of the Service, including, but not limited to, the Application will be governed by and construed in accordance with the laws of Singapore, applicable to agreements made and to be entirely performed within Singapore, without resort to its conflict of law provisions. In the event of any matter or dispute arising out of or in connection with these Terms, you and Classrr will submit to the exclusive jurisdiction of the state and federal courts in Singapore.</p>
                        <h2>Miscellaneous</h2>
                        <p>If any part of these Terms is determined to be invalid or unenforceable pursuant to applicable law, including, without limitation, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of these Terms will continue in full effect. Only you and Classrr are entitled to enforce these Terms. No third party will be entitled to enforce any of the terms and conditions herein.</p>
                        <h2>Final Provision</h2>
                        <p>The English text of these User Terms constitutes the sole authentic text. In the event of any discrepancy between the English text and a translation into a foreign language, the English text shall prevail.</p>
                        <h2>Contact</h2>
                        <p>Please contact us at <a href="mailto:contact@classrr.com">contact@classrr.com</a> with any questions regarding these Terms.</p>
                        <p>Your continued use of this Site and registration to use our Services is contingent upon your agreement to be bound by the foregoing Terms of Use.</p>
                    </div>
                </div><!-- Edn row -->
            </div><!-- End col-lg-9-->
        </div>
    </div><!-- End container -->
@endsection